import 'package:flutter/cupertino.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

//Change the icons as your app needs
IconData getCategoryIcon(String? iconString) {
  switch (iconString) {
    case 'fa-tshirt':
      return FontAwesomeIcons.tshirt;
    case 'fa-hot-tub':
      return FontAwesomeIcons.hotTub;
    case 'fa-skiing':
      return FontAwesomeIcons.skiing;
    case 'fa-dog':
      return FontAwesomeIcons.dog;
    case 'fa-accessible-icon':
      return FontAwesomeIcons.accessibleIcon;
    case 'fa-accusoft':
      return FontAwesomeIcons.accusoft;
    case 'fa-address-book':
      return FontAwesomeIcons.addressBook;
    case 'fa-address-card':
      return FontAwesomeIcons.addressCard;
    case 'fa-adjust':
      return FontAwesomeIcons.adjust;
    case 'fa-adn':
      return FontAwesomeIcons.adn;
    case 'fa-adversal':
      return FontAwesomeIcons.adversal;
    case 'fa-affiliatetheme':
      return FontAwesomeIcons.affiliatetheme;
    case 'fa-algolia':
      return FontAwesomeIcons.algolia;
    case 'fa-align-center':
      return FontAwesomeIcons.alignCenter;
    case 'fa-align-justify':
      return FontAwesomeIcons.alignJustify;
    case 'fa-align-left':
      return FontAwesomeIcons.alignLeft;
    case 'fa-align-right':
      return FontAwesomeIcons.alignRight;
    case 'fa-amazon':
      return FontAwesomeIcons.amazon;
    case 'fa-ambulance':
      return FontAwesomeIcons.ambulance;
    case 'fa-american-sign-language-interpreting':
      return FontAwesomeIcons.americanSignLanguageInterpreting;
    case 'fa-amilia':
      return FontAwesomeIcons.amilia;
    case 'fa-anchor':
      return FontAwesomeIcons.anchor;
    case 'fa-android':
      return FontAwesomeIcons.android;
    case 'fa-angellist':
      return FontAwesomeIcons.angellist;
    case 'fa-angle-double-down':
      return FontAwesomeIcons.angleDoubleDown;
    case 'fa-angle-double-left':
      return FontAwesomeIcons.angleDoubleLeft;
    case 'fa-angle-double-right':
      return FontAwesomeIcons.angleDoubleRight;
    case 'fa-angle-double-up':
      return FontAwesomeIcons.angleDoubleUp;
    case 'fa-angle-down':
      return FontAwesomeIcons.angleDown;
    case 'fa-angle-left':
      return FontAwesomeIcons.angleLeft;
    case 'fa-angle-right':
      return FontAwesomeIcons.angleRight;
    case 'fa-angle-up':
      return FontAwesomeIcons.angleUp;
    case 'fa-angrycreative':
      return FontAwesomeIcons.angrycreative;
    case 'fa-angular':
      return FontAwesomeIcons.angular;
    case 'fa-app-store':
      return FontAwesomeIcons.appStore;
    case 'fa-app-store-ios':
      return FontAwesomeIcons.appStoreIos;
    case 'fa-apper':
      return FontAwesomeIcons.apper;
    case 'fa-apple':
      return FontAwesomeIcons.apple;
    case 'fa-apple-pay':
      return FontAwesomeIcons.applePay;
    case 'fa-archive':
      return FontAwesomeIcons.archive;
    case 'fa-arrow-alt-circle-down':
      return FontAwesomeIcons.arrowAltCircleDown;
    case 'fa-arrow-alt-circle-left':
      return FontAwesomeIcons.arrowAltCircleLeft;
    case 'fa-arrow-alt-circle-right':
      return FontAwesomeIcons.arrowAltCircleRight;
    case 'fa-arrow-alt-circle-up':
      return FontAwesomeIcons.arrowAltCircleUp;
    case 'fa-arrow-circle-down':
      return FontAwesomeIcons.arrowCircleDown;
    case 'fa-arrow-circle-left':
      return FontAwesomeIcons.arrowCircleLeft;
    case 'fa-arrow-circle-right':
      return FontAwesomeIcons.arrowCircleRight;
    case 'fa-arrow-circle-up':
      return FontAwesomeIcons.arrowCircleUp;
    case 'fa-arrow-down':
      return FontAwesomeIcons.arrowDown;
    case 'fa-arrow-left':
      return FontAwesomeIcons.arrowLeft;
    case 'fa-arrow-right':
      return FontAwesomeIcons.arrowRight;
    case 'fa-arrow-up':
      return FontAwesomeIcons.arrowUp;
    case 'fa-arrows-alt':
      return FontAwesomeIcons.arrowsAlt;
    case 'fa-arrows-alt-h':
      return FontAwesomeIcons.arrowsAltH;
    case 'fa-arrows-alt-v':
      return FontAwesomeIcons.arrowsAltV;
    case 'fa-assistive-listening-systems':
      return FontAwesomeIcons.assistiveListeningSystems;
    case 'fa-asterisk':
      return FontAwesomeIcons.asterisk;
    case 'fa-asymmetrik':
      return FontAwesomeIcons.asymmetrik;
    case 'fa-at':
      return FontAwesomeIcons.at;
    case 'fa-audible':
      return FontAwesomeIcons.audible;
    case 'fa-audio-description':
      return FontAwesomeIcons.audioDescription;
    case 'fa-autoprefixer':
      return FontAwesomeIcons.autoprefixer;
    case 'fa-avianex':
      return FontAwesomeIcons.avianex;
    case 'fa-aviato':
      return FontAwesomeIcons.aviato;
    case 'fa-aws':
      return FontAwesomeIcons.aws;
    case 'fa-backward':
      return FontAwesomeIcons.backward;
    case 'fa-balance-scale':
      return FontAwesomeIcons.balanceScale;
    case 'fa-ban':
      return FontAwesomeIcons.ban;
    case 'fa-bandcamp':
      return FontAwesomeIcons.bandcamp;
    case 'fa-barcode':
      return FontAwesomeIcons.barcode;
    case 'fa-bars':
      return FontAwesomeIcons.bars;
    case 'fa-bath':
      return FontAwesomeIcons.bath;
    case 'fa-battery-empty':
      return FontAwesomeIcons.batteryEmpty;
    case 'fa-battery-full':
      return FontAwesomeIcons.batteryFull;
    case 'fa-battery-half':
      return FontAwesomeIcons.batteryHalf;
    case 'fa-battery-quarter':
      return FontAwesomeIcons.batteryQuarter;
    case 'fa-battery-three-quarters':
      return FontAwesomeIcons.batteryThreeQuarters;
    case 'fa-bed':
      return FontAwesomeIcons.bed;
    case 'fa-beer':
      return FontAwesomeIcons.beer;
    case 'fa-behance':
      return FontAwesomeIcons.behance;
    case 'fa-behance-square':
      return FontAwesomeIcons.behanceSquare;
    case 'fa-bell':
      return FontAwesomeIcons.bell;
    case 'fa-bell-slash':
      return FontAwesomeIcons.bellSlash;
    case 'fa-bicycle':
      return FontAwesomeIcons.bicycle;
    case 'fa-bimobject':
      return FontAwesomeIcons.bimobject;
    case 'fa-binoculars':
      return FontAwesomeIcons.binoculars;
    case 'fa-birthday-cake':
      return FontAwesomeIcons.birthdayCake;
    case 'fa-bitbucket':
      return FontAwesomeIcons.bitbucket;
    case 'fa-bitcoin':
      return FontAwesomeIcons.bitcoin;
    case 'fa-bity':
      return FontAwesomeIcons.bity;
    case 'fa-black-tie':
      return FontAwesomeIcons.blackTie;
    case 'fa-blackberry':
      return FontAwesomeIcons.blackberry;
    case 'fa-blind':
      return FontAwesomeIcons.blind;
    case 'fa-blogger':
      return FontAwesomeIcons.blogger;
    case 'fa-blogger-b':
      return FontAwesomeIcons.bloggerB;
    case 'fa-bluetooth':
      return FontAwesomeIcons.bluetooth;
    case 'fa-bluetooth-b':
      return FontAwesomeIcons.bluetoothB;
    case 'fa-bold':
      return FontAwesomeIcons.bold;
    case 'fa-bolt':
      return FontAwesomeIcons.bolt;
    case 'fa-bomb':
      return FontAwesomeIcons.bomb;
    case 'fa-book':
      return FontAwesomeIcons.book;
    case 'fa-bookmark':
      return FontAwesomeIcons.bookmark;
    case 'fa-braille':
      return FontAwesomeIcons.braille;
    case 'fa-briefcase':
      return FontAwesomeIcons.briefcase;
    case 'fa-btc':
      return FontAwesomeIcons.btc;
    case 'fa-bug':
      return FontAwesomeIcons.bug;
    case 'fa-building':
      return FontAwesomeIcons.building;
    case 'fa-bullhorn':
      return FontAwesomeIcons.bullhorn;
    case 'fa-bullseye':
      return FontAwesomeIcons.bullseye;
    case 'fa-buromobelexperte':
      return FontAwesomeIcons.buromobelexperte;
    case 'fa-bus':
      return FontAwesomeIcons.bus;
    case 'fa-buysellads':
      return FontAwesomeIcons.buysellads;
    case 'fa-calculator':
      return FontAwesomeIcons.calculator;
    case 'fa-calendar':
      return FontAwesomeIcons.calendar;
    case 'fa-calendar-alt':
      return FontAwesomeIcons.calendarAlt;
    case 'fa-calendar-check':
      return FontAwesomeIcons.calendarCheck;
    case 'fa-calendar-minus':
      return FontAwesomeIcons.calendarMinus;
    case 'fa-calendar-plus':
      return FontAwesomeIcons.calendarPlus;
    case 'fa-calendar-times':
      return FontAwesomeIcons.calendarTimes;
    case 'fa-camera':
      return FontAwesomeIcons.camera;
    case 'fa-camera-retro':
      return FontAwesomeIcons.cameraRetro;
    case 'fa-car':
      return FontAwesomeIcons.car;
    case 'fa-caret-down':
      return FontAwesomeIcons.caretDown;
    case 'fa-caret-left':
      return FontAwesomeIcons.caretLeft;
    case 'fa-caret-right':
      return FontAwesomeIcons.caretRight;
    case 'fa-caret-square-down':
      return FontAwesomeIcons.caretSquareDown;
    case 'fa-caret-square-left':
      return FontAwesomeIcons.caretSquareLeft;
    case 'fa-caret-square-right':
      return FontAwesomeIcons.caretSquareRight;
    case 'fa-caret-square-up':
      return FontAwesomeIcons.caretSquareUp;
    case 'fa-caret-up':
      return FontAwesomeIcons.caretUp;
    case 'fa-cart-arrow-down':
      return FontAwesomeIcons.cartArrowDown;
    case 'fa-cart-plus':
      return FontAwesomeIcons.cartPlus;
    case 'fa-cc-amex':
      return FontAwesomeIcons.ccAmex;
    case 'fa-cc-apple-pay':
      return FontAwesomeIcons.ccApplePay;
    case 'fa-cc-diners-club':
      return FontAwesomeIcons.ccDinersClub;
    case 'fa-cc-discover':
      return FontAwesomeIcons.ccDiscover;
    case 'fa-cc-jcb':
      return FontAwesomeIcons.ccJcb;
    case 'fa-cc-mastercard':
      return FontAwesomeIcons.ccMastercard;
    case 'fa-cc-paypal':
      return FontAwesomeIcons.ccPaypal;
    case 'fa-cc-stripe':
      return FontAwesomeIcons.ccStripe;
    case 'fa-cc-visa':
      return FontAwesomeIcons.ccVisa;
    case 'fa-centercode':
      return FontAwesomeIcons.centercode;
    case 'fa-certificate':
      return FontAwesomeIcons.certificate;
    case 'fa-chart-area':
      return FontAwesomeIcons.chartArea;
    case 'fa-chart-bar':
      return FontAwesomeIcons.chartBar;
    case 'fa-chart-line':
      return FontAwesomeIcons.chartLine;
    case 'fa-chart-pie':
      return FontAwesomeIcons.chartPie;
    case 'fa-check':
      return FontAwesomeIcons.check;
    case 'fa-check-circle':
      return FontAwesomeIcons.checkCircle;
    case 'fa-check-square':
      return FontAwesomeIcons.checkSquare;
    case 'fa-chevron-circle-down':
      return FontAwesomeIcons.chevronCircleDown;
    case 'fa-chevron-circle-left':
      return FontAwesomeIcons.chevronCircleLeft;
    case 'fa-chevron-circle-right':
      return FontAwesomeIcons.chevronCircleRight;
    case 'fa-chevron-circle-up':
      return FontAwesomeIcons.chevronCircleUp;
    case 'fa-chevron-down':
      return FontAwesomeIcons.chevronDown;
    case 'fa-chevron-left':
      return FontAwesomeIcons.chevronLeft;
    case 'fa-chevron-right':
      return FontAwesomeIcons.chevronRight;
    case 'fa-chevron-up':
      return FontAwesomeIcons.chevronUp;
    case 'fa-child':
      return FontAwesomeIcons.child;
    case 'fa-chrome':
      return FontAwesomeIcons.chrome;
    case 'fa-circle':
      return FontAwesomeIcons.circle;
    case 'fa-circle-notch':
      return FontAwesomeIcons.circleNotch;
    case 'fa-clipboard':
      return FontAwesomeIcons.clipboard;
    case 'fa-clock':
      return FontAwesomeIcons.clock;
    case 'fa-clone':
      return FontAwesomeIcons.clone;
    case 'fa-closed-captioning':
      return FontAwesomeIcons.closedCaptioning;
    case 'fa-cloud':
      return FontAwesomeIcons.cloud;
    case 'fa-cloud-download-alt':
      return FontAwesomeIcons.cloudDownloadAlt;
    case 'fa-cloud-upload-alt':
      return FontAwesomeIcons.cloudUploadAlt;
    case 'fa-cloudscale':
      return FontAwesomeIcons.cloudscale;
    case 'fa-cloudsmith':
      return FontAwesomeIcons.cloudsmith;
    case 'fa-cloudversify':
      return FontAwesomeIcons.cloudversify;
    case 'fa-code':
      return FontAwesomeIcons.code;
    case 'fa-code-branch':
      return FontAwesomeIcons.codeBranch;
    case 'fa-codepen':
      return FontAwesomeIcons.codepen;
    case 'fa-codiepie':
      return FontAwesomeIcons.codiepie;
    case 'fa-coffee':
      return FontAwesomeIcons.coffee;
    case 'fa-cog':
      return FontAwesomeIcons.cog;
    case 'fa-cogs':
      return FontAwesomeIcons.cogs;
    case 'fa-columns':
      return FontAwesomeIcons.columns;
    case 'fa-comment':
      return FontAwesomeIcons.comment;
    case 'fa-comment-alt':
      return FontAwesomeIcons.commentAlt;
    case 'fa-comments':
      return FontAwesomeIcons.comments;
    case 'fa-compass':
      return FontAwesomeIcons.compass;
    case 'fa-compress':
      return FontAwesomeIcons.compress;
    case 'fa-connectdevelop':
      return FontAwesomeIcons.connectdevelop;
    case 'fa-contao':
      return FontAwesomeIcons.contao;
    case 'fa-copy':
      return FontAwesomeIcons.copy;
    case 'fa-copyright':
      return FontAwesomeIcons.copyright;
    case 'fa-cpanel':
      return FontAwesomeIcons.cpanel;
    case 'fa-creative-commons':
      return FontAwesomeIcons.creativeCommons;
    case 'fa-credit-card':
      return FontAwesomeIcons.creditCard;
    case 'fa-crop':
      return FontAwesomeIcons.crop;
    case 'fa-crosshairs':
      return FontAwesomeIcons.crosshairs;
    case 'fa-css3':
      return FontAwesomeIcons.css3;
    case 'fa-css3-alt':
      return FontAwesomeIcons.css3Alt;
    case 'fa-cube':
      return FontAwesomeIcons.cube;
    case 'fa-cubes':
      return FontAwesomeIcons.cubes;
    case 'fa-cut':
      return FontAwesomeIcons.cut;
    case 'fa-cuttlefish':
      return FontAwesomeIcons.cuttlefish;
    case 'fa-d-and-d':
      return FontAwesomeIcons.dAndD;
    case 'fa-dashcube':
      return FontAwesomeIcons.dashcube;
    case 'fa-database':
      return FontAwesomeIcons.database;
    case 'fa-deaf':
      return FontAwesomeIcons.deaf;
    case 'fa-delicious':
      return FontAwesomeIcons.delicious;
    case 'fa-deploydog':
      return FontAwesomeIcons.deploydog;
    case 'fa-deskpro':
      return FontAwesomeIcons.deskpro;
    case 'fa-desktop':
      return FontAwesomeIcons.desktop;
    case 'fa-deviantart':
      return FontAwesomeIcons.deviantart;
    case 'fa-digg':
      return FontAwesomeIcons.digg;
    case 'fa-digital-ocean':
      return FontAwesomeIcons.digitalOcean;
    case 'fa-discord':
      return FontAwesomeIcons.discord;
    case 'fa-discourse':
      return FontAwesomeIcons.discourse;
    case 'fa-dochub':
      return FontAwesomeIcons.dochub;
    case 'fa-docker':
      return FontAwesomeIcons.docker;
    case 'fa-dollar-sign':
      return FontAwesomeIcons.dollarSign;
    case 'fa-dot-circle':
      return FontAwesomeIcons.dotCircle;
    case 'fa-download':
      return FontAwesomeIcons.download;
    case 'fa-draft2digital':
      return FontAwesomeIcons.draft2digital;
    case 'fa-dribbble':
      return FontAwesomeIcons.dribbble;
    case 'fa-dribbble-square':
      return FontAwesomeIcons.dribbbleSquare;
    case 'fa-dropbox':
      return FontAwesomeIcons.dropbox;
    case 'fa-drupal':
      return FontAwesomeIcons.drupal;
    case 'fa-dyalog':
      return FontAwesomeIcons.dyalog;
    case 'fa-earlybirds':
      return FontAwesomeIcons.earlybirds;
    case 'fa-edge':
      return FontAwesomeIcons.edge;
    case 'fa-edit':
      return FontAwesomeIcons.edit;
    case 'fa-eject':
      return FontAwesomeIcons.eject;
    case 'fa-ellipsis-h':
      return FontAwesomeIcons.ellipsisH;
    case 'fa-ellipsis-v':
      return FontAwesomeIcons.ellipsisV;
    case 'fa-ember':
      return FontAwesomeIcons.ember;
    case 'fa-empire':
      return FontAwesomeIcons.empire;
    case 'fa-envelope':
      return FontAwesomeIcons.envelope;
    case 'fa-envelope-open':
      return FontAwesomeIcons.envelopeOpen;
    case 'fa-envelope-square':
      return FontAwesomeIcons.envelopeSquare;
    case 'fa-envira':
      return FontAwesomeIcons.envira;
    case 'fa-eraser':
      return FontAwesomeIcons.eraser;
    case 'fa-erlang':
      return FontAwesomeIcons.erlang;
    case 'fa-etsy':
      return FontAwesomeIcons.etsy;
    case 'fa-euro-sign':
      return FontAwesomeIcons.euroSign;
    case 'fa-exchange-alt':
      return FontAwesomeIcons.exchangeAlt;
    case 'fa-exclamation':
      return FontAwesomeIcons.exclamation;
    case 'fa-exclamation-circle':
      return FontAwesomeIcons.exclamationCircle;
    case 'fa-exclamation-triangle':
      return FontAwesomeIcons.exclamationTriangle;
    case 'fa-expand':
      return FontAwesomeIcons.expand;
    case 'fa-expand-arrows-alt':
      return FontAwesomeIcons.expandArrowsAlt;
    case 'fa-expeditedssl':
      return FontAwesomeIcons.expeditedssl;
    case 'fa-external-link-alt':
      return FontAwesomeIcons.externalLinkAlt;
    case 'fa-external-link-square-alt':
      return FontAwesomeIcons.externalLinkSquareAlt;
    case 'fa-eye':
      return FontAwesomeIcons.eye;
    case 'fa-eye-dropper':
      return FontAwesomeIcons.eyeDropper;
    case 'fa-eye-slash':
      return FontAwesomeIcons.eyeSlash;
    case 'fa-facebook':
      return FontAwesomeIcons.facebook;
    case 'fa-facebook-f':
      return FontAwesomeIcons.facebookF;
    case 'fa-facebook-messenger':
      return FontAwesomeIcons.facebookMessenger;
    case 'fa-facebook-square':
      return FontAwesomeIcons.facebookSquare;
    case 'fa-fast-backward':
      return FontAwesomeIcons.fastBackward;
    case 'fa-fast-forward':
      return FontAwesomeIcons.fastForward;
    case 'fa-fax':
      return FontAwesomeIcons.fax;
    case 'fa-female':
      return FontAwesomeIcons.female;
    case 'fa-fighter-jet':
      return FontAwesomeIcons.fighterJet;
    case 'fa-file':
      return FontAwesomeIcons.file;
    case 'fa-file-alt':
      return FontAwesomeIcons.fileAlt;
    case 'fa-file-archive':
      return FontAwesomeIcons.fileArchive;
    case 'fa-file-audio':
      return FontAwesomeIcons.fileAudio;
    case 'fa-file-code':
      return FontAwesomeIcons.fileCode;
    case 'fa-file-excel':
      return FontAwesomeIcons.fileExcel;
    case 'fa-file-image':
      return FontAwesomeIcons.fileImage;
    case 'fa-file-pdf':
      return FontAwesomeIcons.filePdf;
    case 'fa-file-powerpoint':
      return FontAwesomeIcons.filePowerpoint;
    case 'fa-file-video':
      return FontAwesomeIcons.fileVideo;
    case 'fa-file-word':
      return FontAwesomeIcons.fileWord;
    case 'fa-film':
      return FontAwesomeIcons.film;
    case 'fa-filter':
      return FontAwesomeIcons.filter;
    case 'fa-fire':
      return FontAwesomeIcons.fire;
    case 'fa-fire-extinguisher':
      return FontAwesomeIcons.fireExtinguisher;
    case 'fa-firefox':
      return FontAwesomeIcons.firefox;
    case 'fa-first-order':
      return FontAwesomeIcons.firstOrder;
    case 'fa-firstdraft':
      return FontAwesomeIcons.firstdraft;
    case 'fa-flag':
      return FontAwesomeIcons.flag;
    case 'fa-flag-checkered':
      return FontAwesomeIcons.flagCheckered;
    case 'fa-flask':
      return FontAwesomeIcons.flask;
    case 'fa-flickr':
      return FontAwesomeIcons.flickr;
    case 'fa-fly':
      return FontAwesomeIcons.fly;
    case 'fa-folder':
      return FontAwesomeIcons.folder;
    case 'fa-folder-open':
      return FontAwesomeIcons.folderOpen;
    case 'fa-font':
      return FontAwesomeIcons.font;
    case 'fa-font-awesome':
      return FontAwesomeIcons.fontAwesome;
    case 'fa-font-awesome-alt':
      return FontAwesomeIcons.fontAwesomeAlt;
    case 'fa-font-awesome-flag':
      return FontAwesomeIcons.fontAwesomeFlag;
    case 'fa-fonticons':
      return FontAwesomeIcons.fonticons;
    case 'fa-fonticons-fi':
      return FontAwesomeIcons.fonticonsFi;
    case 'fa-fort-awesome':
      return FontAwesomeIcons.fortAwesome;
    case 'fa-fort-awesome-alt':
      return FontAwesomeIcons.fortAwesomeAlt;
    case 'fa-forumbee':
      return FontAwesomeIcons.forumbee;
    case 'fa-forward':
      return FontAwesomeIcons.forward;
    case 'fa-foursquare':
      return FontAwesomeIcons.foursquare;
    case 'fa-free-code-camp':
      return FontAwesomeIcons.freeCodeCamp;
    case 'fa-freebsd':
      return FontAwesomeIcons.freebsd;
    case 'fa-frown':
      return FontAwesomeIcons.frown;
    case 'fa-futbol':
      return FontAwesomeIcons.futbol;
    case 'fa-gamepad':
      return FontAwesomeIcons.gamepad;
    case 'fa-gavel':
      return FontAwesomeIcons.gavel;
    case 'fa-gem':
      return FontAwesomeIcons.gem;
    case 'fa-genderless':
      return FontAwesomeIcons.genderless;
    case 'fa-get-pocket':
      return FontAwesomeIcons.getPocket;
    case 'fa-gg':
      return FontAwesomeIcons.gg;
    case 'fa-gg-circle':
      return FontAwesomeIcons.ggCircle;
    case 'fa-gift':
      return FontAwesomeIcons.gift;
    case 'fa-git':
      return FontAwesomeIcons.git;
    case 'fa-git-square':
      return FontAwesomeIcons.gitSquare;
    case 'fa-github':
      return FontAwesomeIcons.github;
    case 'fa-github-alt':
      return FontAwesomeIcons.githubAlt;
    case 'fa-github-square':
      return FontAwesomeIcons.githubSquare;
    case 'fa-gitkraken':
      return FontAwesomeIcons.gitkraken;
    case 'fa-gitlab':
      return FontAwesomeIcons.gitlab;
    case 'fa-gitter':
      return FontAwesomeIcons.gitter;
    case 'fa-glass-martini':
      return FontAwesomeIcons.glassMartini;
    case 'fa-glide':
      return FontAwesomeIcons.glide;
    case 'fa-glide-g':
      return FontAwesomeIcons.glideG;
    case 'fa-globe':
      return FontAwesomeIcons.globe;
    case 'fa-gofore':
      return FontAwesomeIcons.gofore;
    case 'fa-goodreads':
      return FontAwesomeIcons.goodreads;
    case 'fa-goodreads-g':
      return FontAwesomeIcons.goodreadsG;
    case 'fa-google':
      return FontAwesomeIcons.google;
    case 'fa-google-drive':
      return FontAwesomeIcons.googleDrive;
    case 'fa-google-play':
      return FontAwesomeIcons.googlePlay;
    case 'fa-google-plus':
      return FontAwesomeIcons.googlePlus;
    case 'fa-google-plus-g':
      return FontAwesomeIcons.googlePlusG;
    case 'fa-google-plus-square':
      return FontAwesomeIcons.googlePlusSquare;
    case 'fa-google-wallet':
      return FontAwesomeIcons.googleWallet;
    case 'fa-graduation-cap':
      return FontAwesomeIcons.graduationCap;
    case 'fa-gratipay':
      return FontAwesomeIcons.gratipay;
    case 'fa-grav':
      return FontAwesomeIcons.grav;
    case 'fa-gripfire':
      return FontAwesomeIcons.gripfire;
    case 'fa-grunt':
      return FontAwesomeIcons.grunt;
    case 'fa-gulp':
      return FontAwesomeIcons.gulp;
    case 'fa-h-square':
      return FontAwesomeIcons.hSquare;
    case 'fa-hacker-news':
      return FontAwesomeIcons.hackerNews;
    case 'fa-hacker-news-square':
      return FontAwesomeIcons.hackerNewsSquare;
    case 'fa-hand-lizard':
      return FontAwesomeIcons.handLizard;
    case 'fa-hand-paper':
      return FontAwesomeIcons.handPaper;
    case 'fa-hand-peace':
      return FontAwesomeIcons.handPeace;
    case 'fa-hand-point-down':
      return FontAwesomeIcons.handPointDown;
    case 'fa-hand-point-left':
      return FontAwesomeIcons.handPointLeft;
    case 'fa-hand-point-right':
      return FontAwesomeIcons.handPointRight;
    case 'fa-hand-point-up':
      return FontAwesomeIcons.handPointUp;
    case 'fa-hand-pointer':
      return FontAwesomeIcons.handPointer;
    case 'fa-hand-rock':
      return FontAwesomeIcons.handRock;
    case 'fa-hand-scissors':
      return FontAwesomeIcons.handScissors;
    case 'fa-hand-spock':
      return FontAwesomeIcons.handSpock;
    case 'fa-handshake':
      return FontAwesomeIcons.handshake;
    case 'fa-hashtag':
      return FontAwesomeIcons.hashtag;
    case 'fa-hdd':
      return FontAwesomeIcons.hdd;
    case 'fa-heading':
      return FontAwesomeIcons.heading;
    case 'fa-headphones':
      return FontAwesomeIcons.headphones;
    case 'fa-heart':
      return FontAwesomeIcons.heart;
    case 'fa-heartbeat':
      return FontAwesomeIcons.heartbeat;
    case 'fa-hire-a-helper':
      return FontAwesomeIcons.hireAHelper;
    case 'fa-history':
      return FontAwesomeIcons.history;
    case 'fa-home':
      return FontAwesomeIcons.home;
    case 'fa-hooli':
      return FontAwesomeIcons.hooli;
    case 'fa-hospital':
      return FontAwesomeIcons.hospital;
    case 'fa-hotjar':
      return FontAwesomeIcons.hotjar;
    case 'fa-hourglass':
      return FontAwesomeIcons.hourglass;
    case 'fa-hourglass-end':
      return FontAwesomeIcons.hourglassEnd;
    case 'fa-hourglass-half':
      return FontAwesomeIcons.hourglassHalf;
    case 'fa-hourglass-start':
      return FontAwesomeIcons.hourglassStart;
    case 'fa-houzz':
      return FontAwesomeIcons.houzz;
    case 'fa-html5':
      return FontAwesomeIcons.html5;
    case 'fa-hubspot':
      return FontAwesomeIcons.hubspot;
    case 'fa-i-cursor':
      return FontAwesomeIcons.iCursor;
    case 'fa-id-badge':
      return FontAwesomeIcons.idBadge;
    case 'fa-id-card':
      return FontAwesomeIcons.idCard;
    case 'fa-image':
      return FontAwesomeIcons.image;
    case 'fa-images':
      return FontAwesomeIcons.images;
    case 'fa-imdb':
      return FontAwesomeIcons.imdb;
    case 'fa-inbox':
      return FontAwesomeIcons.inbox;
    case 'fa-indent':
      return FontAwesomeIcons.indent;
    case 'fa-industry':
      return FontAwesomeIcons.industry;
    case 'fa-info':
      return FontAwesomeIcons.info;
    case 'fa-info-circle':
      return FontAwesomeIcons.infoCircle;
    case 'fa-instagram':
      return FontAwesomeIcons.instagram;
    case 'fa-internet-explorer':
      return FontAwesomeIcons.internetExplorer;
    case 'fa-ioxhost':
      return FontAwesomeIcons.ioxhost;
    case 'fa-italic':
      return FontAwesomeIcons.italic;
    case 'fa-itunes':
      return FontAwesomeIcons.itunes;
    case 'fa-itunes-note':
      return FontAwesomeIcons.itunesNote;
    case 'fa-jenkins':
      return FontAwesomeIcons.jenkins;
    case 'fa-joget':
      return FontAwesomeIcons.joget;
    case 'fa-joomla':
      return FontAwesomeIcons.joomla;
    case 'fa-js':
      return FontAwesomeIcons.js;
    case 'fa-js-square':
      return FontAwesomeIcons.jsSquare;
    case 'fa-jsfiddle':
      return FontAwesomeIcons.jsfiddle;
    case 'fa-key':
      return FontAwesomeIcons.key;
    case 'fa-keyboard':
      return FontAwesomeIcons.keyboard;
    case 'fa-keycdn':
      return FontAwesomeIcons.keycdn;
    case 'fa-kickstarter':
      return FontAwesomeIcons.kickstarter;
    case 'fa-kickstarter-k':
      return FontAwesomeIcons.kickstarterK;
    case 'fa-language':
      return FontAwesomeIcons.language;
    case 'fa-laptop':
      return FontAwesomeIcons.laptop;
    case 'fa-laravel':
      return FontAwesomeIcons.laravel;
    case 'fa-lastfm':
      return FontAwesomeIcons.lastfm;
    case 'fa-lastfm-square':
      return FontAwesomeIcons.lastfmSquare;
    case 'fa-leaf':
      return FontAwesomeIcons.leaf;
    case 'fa-leanpub':
      return FontAwesomeIcons.leanpub;
    case 'fa-lemon':
      return FontAwesomeIcons.lemon;
    case 'fa-less':
      return FontAwesomeIcons.less;
    case 'fa-level-down-alt':
      return FontAwesomeIcons.levelDownAlt;
    case 'fa-level-up-alt':
      return FontAwesomeIcons.levelUpAlt;
    case 'fa-life-ring':
      return FontAwesomeIcons.lifeRing;
    case 'fa-lightbulb':
      return FontAwesomeIcons.lightbulb;
    case 'fa-line':
      return FontAwesomeIcons.line;
    case 'fa-link':
      return FontAwesomeIcons.link;
    case 'fa-linkedin':
      return FontAwesomeIcons.linkedin;
    case 'fa-linkedin-in':
      return FontAwesomeIcons.linkedinIn;
    case 'fa-linode':
      return FontAwesomeIcons.linode;
    case 'fa-linux':
      return FontAwesomeIcons.linux;
    case 'fa-lira-sign':
      return FontAwesomeIcons.liraSign;
    case 'fa-list':
      return FontAwesomeIcons.list;
    case 'fa-list-alt':
      return FontAwesomeIcons.listAlt;
    case 'fa-list-ol':
      return FontAwesomeIcons.listOl;
    case 'fa-list-ul':
      return FontAwesomeIcons.listUl;
    case 'fa-location-arrow':
      return FontAwesomeIcons.locationArrow;
    case 'fa-lock':
      return FontAwesomeIcons.lock;
    case 'fa-lock-open':
      return FontAwesomeIcons.lockOpen;
    case 'fa-long-arrow-alt-down':
      return FontAwesomeIcons.longArrowAltDown;
    case 'fa-long-arrow-alt-left':
      return FontAwesomeIcons.longArrowAltLeft;
    case 'fa-long-arrow-alt-right':
      return FontAwesomeIcons.longArrowAltRight;
    case 'fa-long-arrow-alt-up':
      return FontAwesomeIcons.longArrowAltUp;
    case 'fa-low-vision':
      return FontAwesomeIcons.lowVision;
    case 'fa-lyft':
      return FontAwesomeIcons.lyft;
    case 'fa-magento':
      return FontAwesomeIcons.magento;
    case 'fa-magic':
      return FontAwesomeIcons.magic;
    case 'fa-magnet':
      return FontAwesomeIcons.magnet;
    case 'fa-male':
      return FontAwesomeIcons.male;
    case 'fa-map':
      return FontAwesomeIcons.map;
    case 'fa-map-marker':
      return FontAwesomeIcons.mapMarker;
    case 'fa-map-marker-alt':
      return FontAwesomeIcons.mapMarkerAlt;
    case 'fa-map-pin':
      return FontAwesomeIcons.mapPin;
    case 'fa-map-signs':
      return FontAwesomeIcons.mapSigns;
    case 'fa-mars':
      return FontAwesomeIcons.mars;
    case 'fa-mars-double':
      return FontAwesomeIcons.marsDouble;
    case 'fa-mars-stroke':
      return FontAwesomeIcons.marsStroke;
    case 'fa-mars-stroke-h':
      return FontAwesomeIcons.marsStrokeH;
    case 'fa-mars-stroke-v':
      return FontAwesomeIcons.marsStrokeV;
    case 'fa-maxcdn':
      return FontAwesomeIcons.maxcdn;
    case 'fa-medapps':
      return FontAwesomeIcons.medapps;
    case 'fa-medium':
      return FontAwesomeIcons.medium;
    case 'fa-medium-m':
      return FontAwesomeIcons.mediumM;
    case 'fa-medkit':
      return FontAwesomeIcons.medkit;
    case 'fa-medrt':
      return FontAwesomeIcons.medrt;
    case 'fa-meetup':
      return FontAwesomeIcons.meetup;
    case 'fa-meh':
      return FontAwesomeIcons.meh;
    case 'fa-mercury':
      return FontAwesomeIcons.mercury;
    case 'fa-microchip':
      return FontAwesomeIcons.microchip;
    case 'fa-microphone':
      return FontAwesomeIcons.microphone;
    case 'fa-microphone-slash':
      return FontAwesomeIcons.microphoneSlash;
    case 'fa-microsoft':
      return FontAwesomeIcons.microsoft;
    case 'fa-minus':
      return FontAwesomeIcons.minus;
    case 'fa-minus-circle':
      return FontAwesomeIcons.minusCircle;
    case 'fa-minus-square':
      return FontAwesomeIcons.minusSquare;
    case 'fa-mix':
      return FontAwesomeIcons.mix;
    case 'fa-mixcloud':
      return FontAwesomeIcons.mixcloud;
    case 'fa-mizuni':
      return FontAwesomeIcons.mizuni;
    case 'fa-mobile':
      return FontAwesomeIcons.mobile;
    case 'fa-mobile-alt':
      return FontAwesomeIcons.mobileAlt;
    case 'fa-modx':
      return FontAwesomeIcons.modx;
    case 'fa-monero':
      return FontAwesomeIcons.monero;
    case 'fa-money-bill-alt':
      return FontAwesomeIcons.moneyBillAlt;
    case 'fa-moon':
      return FontAwesomeIcons.moon;
    case 'fa-motorcycle':
      return FontAwesomeIcons.motorcycle;
    case 'fa-mouse-pointer':
      return FontAwesomeIcons.mousePointer;
    case 'fa-music':
      return FontAwesomeIcons.music;
    case 'fa-napster':
      return FontAwesomeIcons.napster;
    case 'fa-neuter':
      return FontAwesomeIcons.neuter;
    case 'fa-newspaper':
      return FontAwesomeIcons.newspaper;
    case 'fa-node':
      return FontAwesomeIcons.node;
    case 'fa-node-js':
      return FontAwesomeIcons.nodeJs;
    case 'fa-npm':
      return FontAwesomeIcons.npm;
    case 'fa-ns8':
      return FontAwesomeIcons.ns8;
    case 'fa-nutritionix':
      return FontAwesomeIcons.nutritionix;
    case 'fa-object-group':
      return FontAwesomeIcons.objectGroup;
    case 'fa-object-ungroup':
      return FontAwesomeIcons.objectUngroup;
    case 'fa-odnoklassniki':
      return FontAwesomeIcons.odnoklassniki;
    case 'fa-odnoklassniki-square':
      return FontAwesomeIcons.odnoklassnikiSquare;
    case 'fa-opencart':
      return FontAwesomeIcons.opencart;
    case 'fa-openid':
      return FontAwesomeIcons.openid;
    case 'fa-opera':
      return FontAwesomeIcons.opera;
    case 'fa-optin-monster':
      return FontAwesomeIcons.optinMonster;
    case 'fa-osi':
      return FontAwesomeIcons.osi;
    case 'fa-outdent':
      return FontAwesomeIcons.outdent;
    case 'fa-page4':
      return FontAwesomeIcons.page4;
    case 'fa-pagelines':
      return FontAwesomeIcons.pagelines;
    case 'fa-paint-brush':
      return FontAwesomeIcons.paintBrush;
    case 'fa-palfed':
      return FontAwesomeIcons.palfed;
    case 'fa-paper-plane':
      return FontAwesomeIcons.paperPlane;
    case 'fa-paperclip':
      return FontAwesomeIcons.paperclip;
    case 'fa-paragraph':
      return FontAwesomeIcons.paragraph;
    case 'fa-paste':
      return FontAwesomeIcons.paste;
    case 'fa-patreon':
      return FontAwesomeIcons.patreon;
    case 'fa-pause':
      return FontAwesomeIcons.pause;
    case 'fa-pause-circle':
      return FontAwesomeIcons.pauseCircle;
    case 'fa-paw':
      return FontAwesomeIcons.paw;
    case 'fa-paypal':
      return FontAwesomeIcons.paypal;
    case 'fa-pen-square':
      return FontAwesomeIcons.penSquare;
    case 'fa-pencil-alt':
      return FontAwesomeIcons.pencilAlt;
    case 'fa-percent':
      return FontAwesomeIcons.percent;
    case 'fa-periscope':
      return FontAwesomeIcons.periscope;
    case 'fa-phabricator':
      return FontAwesomeIcons.phabricator;
    case 'fa-phoenix-framework':
      return FontAwesomeIcons.phoenixFramework;
    case 'fa-phone':
      return FontAwesomeIcons.phone;
    case 'fa-phone-square':
      return FontAwesomeIcons.phoneSquare;
    case 'fa-phone-volume':
      return FontAwesomeIcons.phoneVolume;
    case 'fa-pied-piper':
      return FontAwesomeIcons.piedPiper;
    case 'fa-pied-piper-alt':
      return FontAwesomeIcons.piedPiperAlt;
    case 'fa-pied-piper-pp':
      return FontAwesomeIcons.piedPiperPp;
    case 'fa-pinterest':
      return FontAwesomeIcons.pinterest;
    case 'fa-pinterest-p':
      return FontAwesomeIcons.pinterestP;
    case 'fa-pinterest-square':
      return FontAwesomeIcons.pinterestSquare;
    case 'fa-plane':
      return FontAwesomeIcons.plane;
    case 'fa-play':
      return FontAwesomeIcons.play;
    case 'fa-play-circle':
      return FontAwesomeIcons.playCircle;
    case 'fa-playstation':
      return FontAwesomeIcons.playstation;
    case 'fa-plug':
      return FontAwesomeIcons.plug;
    case 'fa-plus':
      return FontAwesomeIcons.plus;
    case 'fa-plus-circle':
      return FontAwesomeIcons.plusCircle;
    case 'fa-plus-square':
      return FontAwesomeIcons.plusSquare;
    case 'fa-podcast':
      return FontAwesomeIcons.podcast;
    case 'fa-pound-sign':
      return FontAwesomeIcons.poundSign;
    case 'fa-power-off':
      return FontAwesomeIcons.powerOff;
    case 'fa-print':
      return FontAwesomeIcons.print;
    case 'fa-product-hunt':
      return FontAwesomeIcons.productHunt;
    case 'fa-pushed':
      return FontAwesomeIcons.pushed;
    case 'fa-puzzle-piece':
      return FontAwesomeIcons.puzzlePiece;
    case 'fa-python':
      return FontAwesomeIcons.python;
    case 'fa-qq':
      return FontAwesomeIcons.qq;
    case 'fa-qrcode':
      return FontAwesomeIcons.qrcode;
    case 'fa-question':
      return FontAwesomeIcons.question;
    case 'fa-question-circle':
      return FontAwesomeIcons.questionCircle;
    case 'fa-quora':
      return FontAwesomeIcons.quora;
    case 'fa-quote-left':
      return FontAwesomeIcons.quoteLeft;
    case 'fa-quote-right':
      return FontAwesomeIcons.quoteRight;
    case 'fa-random':
      return FontAwesomeIcons.random;
    case 'fa-ravelry':
      return FontAwesomeIcons.ravelry;
    case 'fa-react':
      return FontAwesomeIcons.react;
    case 'fa-rebel':
      return FontAwesomeIcons.rebel;
    case 'fa-recycle':
      return FontAwesomeIcons.recycle;
    case 'fa-red-river':
      return FontAwesomeIcons.redRiver;
    case 'fa-reddit':
      return FontAwesomeIcons.reddit;
    case 'fa-reddit-alien':
      return FontAwesomeIcons.redditAlien;
    case 'fa-reddit-square':
      return FontAwesomeIcons.redditSquare;
    case 'fa-redo':
      return FontAwesomeIcons.redo;
    case 'fa-redo-alt':
      return FontAwesomeIcons.redoAlt;
    case 'fa-registered':
      return FontAwesomeIcons.registered;
    case 'fa-renren':
      return FontAwesomeIcons.renren;
    case 'fa-reply':
      return FontAwesomeIcons.reply;
    case 'fa-reply-all':
      return FontAwesomeIcons.replyAll;
    case 'fa-replyd':
      return FontAwesomeIcons.replyd;
    case 'fa-resolving':
      return FontAwesomeIcons.resolving;
    case 'fa-retweet':
      return FontAwesomeIcons.retweet;
    case 'fa-road':
      return FontAwesomeIcons.road;
    case 'fa-rocket':
      return FontAwesomeIcons.rocket;
    case 'fa-rocketchat':
      return FontAwesomeIcons.rocketchat;
    case 'fa-rockrms':
      return FontAwesomeIcons.rockrms;
    case 'fa-rss':
      return FontAwesomeIcons.rss;
    case 'fa-rss-square':
      return FontAwesomeIcons.rssSquare;
    case 'fa-ruble-sign':
      return FontAwesomeIcons.rubleSign;
    case 'fa-rupee-sign':
      return FontAwesomeIcons.rupeeSign;
    case 'fa-safari':
      return FontAwesomeIcons.safari;
    case 'fa-sass':
      return FontAwesomeIcons.sass;
    case 'fa-save':
      return FontAwesomeIcons.save;
    case 'fa-schlix':
      return FontAwesomeIcons.schlix;
    case 'fa-scribd':
      return FontAwesomeIcons.scribd;
    case 'fa-search':
      return FontAwesomeIcons.search;
    case 'fa-search-minus':
      return FontAwesomeIcons.searchMinus;
    case 'fa-search-plus':
      return FontAwesomeIcons.searchPlus;
    case 'fa-searchengin':
      return FontAwesomeIcons.searchengin;
    case 'fa-sellcast':
      return FontAwesomeIcons.sellcast;
    case 'fa-sellsy':
      return FontAwesomeIcons.sellsy;
    case 'fa-server':
      return FontAwesomeIcons.server;
    case 'fa-servicestack':
      return FontAwesomeIcons.servicestack;
    case 'fa-share':
      return FontAwesomeIcons.share;
    case 'fa-share-alt':
      return FontAwesomeIcons.shareAlt;
    case 'fa-share-alt-square':
      return FontAwesomeIcons.shareAltSquare;
    case 'fa-share-square':
      return FontAwesomeIcons.shareSquare;
    case 'fa-shekel-sign':
      return FontAwesomeIcons.shekelSign;
    case 'fa-shield-alt':
      return FontAwesomeIcons.shieldAlt;
    case 'fa-ship':
      return FontAwesomeIcons.ship;
    case 'fa-shirtsinbulk':
      return FontAwesomeIcons.shirtsinbulk;
    case 'fa-shopping-bag':
      return FontAwesomeIcons.shoppingBag;
    case 'fa-shopping-basket':
      return FontAwesomeIcons.shoppingBasket;
    case 'fa-shopping-cart':
      return FontAwesomeIcons.shoppingCart;
    case 'fa-shower':
      return FontAwesomeIcons.shower;
    case 'fa-sign-in-alt':
      return FontAwesomeIcons.signInAlt;
    case 'fa-sign-language':
      return FontAwesomeIcons.signLanguage;
    case 'fa-sign-out-alt':
      return FontAwesomeIcons.signOutAlt;
    case 'fa-signal':
      return FontAwesomeIcons.signal;
    case 'fa-simplybuilt':
      return FontAwesomeIcons.simplybuilt;
    case 'fa-sistrix':
      return FontAwesomeIcons.sistrix;
    case 'fa-sitemap':
      return FontAwesomeIcons.sitemap;
    case 'fa-skyatlas':
      return FontAwesomeIcons.skyatlas;
    case 'fa-skype':
      return FontAwesomeIcons.skype;
    case 'fa-slack':
      return FontAwesomeIcons.slack;
    case 'fa-slack-hash':
      return FontAwesomeIcons.slackHash;
    case 'fa-sliders-h':
      return FontAwesomeIcons.slidersH;
    case 'fa-slideshare':
      return FontAwesomeIcons.slideshare;
    case 'fa-smile':
      return FontAwesomeIcons.smile;
    case 'fa-snapchat':
      return FontAwesomeIcons.snapchat;
    case 'fa-snapchat-ghost':
      return FontAwesomeIcons.snapchatGhost;
    case 'fa-snapchat-square':
      return FontAwesomeIcons.snapchatSquare;
    case 'fa-snowflake':
      return FontAwesomeIcons.snowflake;
    case 'fa-sort':
      return FontAwesomeIcons.sort;
    case 'fa-sort-alpha-down':
      return FontAwesomeIcons.sortAlphaDown;
    case 'fa-sort-alpha-up':
      return FontAwesomeIcons.sortAlphaUp;
    case 'fa-sort-amount-down':
      return FontAwesomeIcons.sortAmountDown;
    case 'fa-sort-amount-up':
      return FontAwesomeIcons.sortAmountUp;
    case 'fa-sort-down':
      return FontAwesomeIcons.sortDown;
    case 'fa-sort-numeric-down':
      return FontAwesomeIcons.sortNumericDown;
    case 'fa-sort-numeric-up':
      return FontAwesomeIcons.sortNumericUp;
    case 'fa-sort-up':
      return FontAwesomeIcons.sortUp;
    case 'fa-soundcloud':
      return FontAwesomeIcons.soundcloud;
    case 'fa-space-shuttle':
      return FontAwesomeIcons.spaceShuttle;
    case 'fa-speakap':
      return FontAwesomeIcons.speakap;
    case 'fa-spinner':
      return FontAwesomeIcons.spinner;
    case 'fa-spotify':
      return FontAwesomeIcons.spotify;
    case 'fa-square':
      return FontAwesomeIcons.square;
    case 'fa-stack-exchange':
      return FontAwesomeIcons.stackExchange;
    case 'fa-stack-overflow':
      return FontAwesomeIcons.stackOverflow;
    case 'fa-star':
      return FontAwesomeIcons.star;
    case 'fa-star-half':
      return FontAwesomeIcons.starHalf;
    case 'fa-staylinked':
      return FontAwesomeIcons.staylinked;
    case 'fa-steam':
      return FontAwesomeIcons.steam;
    case 'fa-steam-square':
      return FontAwesomeIcons.steamSquare;
    case 'fa-steam-symbol':
      return FontAwesomeIcons.steamSymbol;
    case 'fa-step-backward':
      return FontAwesomeIcons.stepBackward;
    case 'fa-step-forward':
      return FontAwesomeIcons.stepForward;
    case 'fa-stethoscope':
      return FontAwesomeIcons.stethoscope;
    case 'fa-sticker-mule':
      return FontAwesomeIcons.stickerMule;
    case 'fa-sticky-note':
      return FontAwesomeIcons.stickyNote;
    case 'fa-stop':
      return FontAwesomeIcons.stop;
    case 'fa-stop-circle':
      return FontAwesomeIcons.stopCircle;
    case 'fa-strava':
      return FontAwesomeIcons.strava;
    case 'fa-street-view':
      return FontAwesomeIcons.streetView;
    case 'fa-strikethrough':
      return FontAwesomeIcons.strikethrough;
    case 'fa-stripe':
      return FontAwesomeIcons.stripe;
    case 'fa-stripe-s':
      return FontAwesomeIcons.stripeS;
    case 'fa-studiovinari':
      return FontAwesomeIcons.studiovinari;
    case 'fa-stumbleupon':
      return FontAwesomeIcons.stumbleupon;
    case 'fa-stumbleupon-circle':
      return FontAwesomeIcons.stumbleuponCircle;
    case 'fa-subscript':
      return FontAwesomeIcons.subscript;
    case 'fa-subway':
      return FontAwesomeIcons.subway;
    case 'fa-suitcase':
      return FontAwesomeIcons.suitcase;
    case 'fa-sun':
      return FontAwesomeIcons.sun;
    case 'fa-superpowers':
      return FontAwesomeIcons.superpowers;
    case 'fa-superscript':
      return FontAwesomeIcons.superscript;
    case 'fa-supple':
      return FontAwesomeIcons.supple;
    case 'fa-sync':
      return FontAwesomeIcons.sync;
    case 'fa-sync-alt':
      return FontAwesomeIcons.syncAlt;
    case 'fa-table':
      return FontAwesomeIcons.table;
    case 'fa-tablet':
      return FontAwesomeIcons.tablet;
    case 'fa-tablet-alt':
      return FontAwesomeIcons.tabletAlt;
    case 'fa-tachometer-alt':
      return FontAwesomeIcons.tachometerAlt;
    case 'fa-tag':
      return FontAwesomeIcons.tag;
    case 'fa-tags':
      return FontAwesomeIcons.tags;
    case 'fa-tasks':
      return FontAwesomeIcons.tasks;
    case 'fa-taxi':
      return FontAwesomeIcons.taxi;
    case 'fa-telegram':
      return FontAwesomeIcons.telegram;
    case 'fa-telegram-plane':
      return FontAwesomeIcons.telegramPlane;
    case 'fa-tencent-weibo':
      return FontAwesomeIcons.tencentWeibo;
    case 'fa-terminal':
      return FontAwesomeIcons.terminal;
    case 'fa-text-height':
      return FontAwesomeIcons.textHeight;
    case 'fa-text-width':
      return FontAwesomeIcons.textWidth;
    case 'fa-th':
      return FontAwesomeIcons.th;
    case 'fa-th-large':
      return FontAwesomeIcons.thLarge;
    case 'fa-th-list':
      return FontAwesomeIcons.thList;
    case 'fa-themeisle':
      return FontAwesomeIcons.themeisle;
    case 'fa-thermometer-empty':
      return FontAwesomeIcons.thermometerEmpty;
    case 'fa-thermometer-full':
      return FontAwesomeIcons.thermometerFull;
    case 'fa-thermometer-half':
      return FontAwesomeIcons.thermometerHalf;
    case 'fa-thermometer-quarter':
      return FontAwesomeIcons.thermometerQuarter;
    case 'fa-thermometer-three-quarters':
      return FontAwesomeIcons.thermometerThreeQuarters;
    case 'fa-thumbs-down':
      return FontAwesomeIcons.thumbsDown;
    case 'fa-thumbs-up':
      return FontAwesomeIcons.thumbsUp;
    case 'fa-thumbtack':
      return FontAwesomeIcons.thumbtack;
    case 'fa-ticket-alt':
      return FontAwesomeIcons.ticketAlt;
    case 'fa-times':
      return FontAwesomeIcons.times;
    case 'fa-times-circle':
      return FontAwesomeIcons.timesCircle;
    case 'fa-tint':
      return FontAwesomeIcons.tint;
    case 'fa-toggle-off':
      return FontAwesomeIcons.toggleOff;
    case 'fa-toggle-on':
      return FontAwesomeIcons.toggleOn;
    case 'fa-trademark':
      return FontAwesomeIcons.trademark;
    case 'fa-train':
      return FontAwesomeIcons.train;
    case 'fa-transgender':
      return FontAwesomeIcons.transgender;
    case 'fa-transgender-alt':
      return FontAwesomeIcons.transgenderAlt;
    case 'fa-trash':
      return FontAwesomeIcons.trash;
    case 'fa-trash-alt':
      return FontAwesomeIcons.trashAlt;
    case 'fa-tree':
      return FontAwesomeIcons.tree;
    case 'fa-trello':
      return FontAwesomeIcons.trello;
    case 'fa-trophy':
      return FontAwesomeIcons.trophy;
    case 'fa-truck':
      return FontAwesomeIcons.truck;
    case 'fa-tty':
      return FontAwesomeIcons.tty;
    case 'fa-tumblr':
      return FontAwesomeIcons.tumblr;
    case 'fa-tumblr-square':
      return FontAwesomeIcons.tumblrSquare;
    case 'fa-tv':
      return FontAwesomeIcons.tv;
    case 'fa-twitch':
      return FontAwesomeIcons.twitch;
    case 'fa-twitter':
      return FontAwesomeIcons.twitter;
    case 'fa-twitter-square':
      return FontAwesomeIcons.twitterSquare;
    case 'fa-typo3':
      return FontAwesomeIcons.typo3;
    case 'fa-uber':
      return FontAwesomeIcons.uber;
    case 'fa-uikit':
      return FontAwesomeIcons.uikit;
    case 'fa-umbrella':
      return FontAwesomeIcons.umbrella;
    case 'fa-underline':
      return FontAwesomeIcons.underline;
    case 'fa-undo':
      return FontAwesomeIcons.undo;
    case 'fa-undo-alt':
      return FontAwesomeIcons.undoAlt;
    case 'fa-uniregistry':
      return FontAwesomeIcons.uniregistry;
    case 'fa-universal-access':
      return FontAwesomeIcons.universalAccess;
    case 'fa-university':
      return FontAwesomeIcons.university;
    case 'fa-unlink':
      return FontAwesomeIcons.unlink;
    case 'fa-unlock':
      return FontAwesomeIcons.unlock;
    case 'fa-unlock-alt':
      return FontAwesomeIcons.unlockAlt;
    case 'fa-untappd':
      return FontAwesomeIcons.untappd;
    case 'fa-upload':
      return FontAwesomeIcons.upload;
    case 'fa-usb':
      return FontAwesomeIcons.usb;
    case 'fa-user':
      return FontAwesomeIcons.user;
    case 'fa-user-circle':
      return FontAwesomeIcons.userCircle;
    case 'fa-user-md':
      return FontAwesomeIcons.userMd;
    case 'fa-user-plus':
      return FontAwesomeIcons.userPlus;
    case 'fa-user-secret':
      return FontAwesomeIcons.userSecret;
    case 'fa-user-times':
      return FontAwesomeIcons.userTimes;
    case 'fa-users':
      return FontAwesomeIcons.users;
    case 'fa-ussunnah':
      return FontAwesomeIcons.ussunnah;
    case 'fa-utensil-spoon':
      return FontAwesomeIcons.utensilSpoon;
    case 'fa-utensils':
      return FontAwesomeIcons.utensils;
    case 'fa-vaadin':
      return FontAwesomeIcons.vaadin;
    case 'fa-venus':
      return FontAwesomeIcons.venus;
    case 'fa-venus-double':
      return FontAwesomeIcons.venusDouble;
    case 'fa-venus-mars':
      return FontAwesomeIcons.venusMars;
    case 'fa-viacoin':
      return FontAwesomeIcons.viacoin;
    case 'fa-viadeo':
      return FontAwesomeIcons.viadeo;
    case 'fa-viadeo-square':
      return FontAwesomeIcons.viadeoSquare;
    case 'fa-viber':
      return FontAwesomeIcons.viber;
    case 'fa-video':
      return FontAwesomeIcons.video;
    case 'fa-vimeo':
      return FontAwesomeIcons.vimeo;
    case 'fa-vimeo-square':
      return FontAwesomeIcons.vimeoSquare;
    case 'fa-vimeo-v':
      return FontAwesomeIcons.vimeoV;
    case 'fa-vine':
      return FontAwesomeIcons.vine;
    case 'fa-vk':
      return FontAwesomeIcons.vk;
    case 'fa-vnv':
      return FontAwesomeIcons.vnv;
    case 'fa-volume-down':
      return FontAwesomeIcons.volumeDown;
    case 'fa-volume-off':
      return FontAwesomeIcons.volumeOff;
    case 'fa-volume-up':
      return FontAwesomeIcons.volumeUp;
    case 'fa-vuejs':
      return FontAwesomeIcons.vuejs;
    case 'fa-weibo':
      return FontAwesomeIcons.weibo;
    case 'fa-weixin':
      return FontAwesomeIcons.weixin;
    case 'fa-whatsapp':
      return FontAwesomeIcons.whatsapp;
    case 'fa-whatsapp-square':
      return FontAwesomeIcons.whatsappSquare;
    case 'fa-wheelchair':
      return FontAwesomeIcons.wheelchair;
    case 'fa-whmcs':
      return FontAwesomeIcons.whmcs;
    case 'fa-wifi':
      return FontAwesomeIcons.wifi;
    case 'fa-wikipedia-w':
      return FontAwesomeIcons.wikipediaW;
    case 'fa-window-close':
      return FontAwesomeIcons.windowClose;
    case 'fa-window-maximize':
      return FontAwesomeIcons.windowMaximize;
    case 'fa-window-minimize':
      return FontAwesomeIcons.windowMinimize;
    case 'fa-window-restore':
      return FontAwesomeIcons.windowRestore;
    case 'fa-windows':
      return FontAwesomeIcons.windows;
    case 'fa-won-sign':
      return FontAwesomeIcons.wonSign;
    case 'fa-wordpress':
      return FontAwesomeIcons.wordpress;
    case 'fa-wordpress-simple':
      return FontAwesomeIcons.wordpressSimple;
    case 'fa-wpbeginner':
      return FontAwesomeIcons.wpbeginner;
    case 'fa-wpexplorer':
      return FontAwesomeIcons.wpexplorer;
    case 'fa-wpforms':
      return FontAwesomeIcons.wpforms;
    case 'fa-wrench':
      return FontAwesomeIcons.wrench;
    case 'fa-xbox':
      return FontAwesomeIcons.xbox;
    case 'fa-xing':
      return FontAwesomeIcons.xing;
    case 'fa-xing-square':
      return FontAwesomeIcons.xingSquare;
    case 'fa-y-combinator':
      return FontAwesomeIcons.yCombinator;
    case 'fa-yahoo':
      return FontAwesomeIcons.yahoo;
    case 'fa-yandex':
      return FontAwesomeIcons.yandex;
    case 'fa-yandex-international':
      return FontAwesomeIcons.yandexInternational;
    case 'fa-yelp':
      return FontAwesomeIcons.yelp;
    case 'fa-yen-sign':
      return FontAwesomeIcons.yenSign;
    case 'fa-yoast':
      return FontAwesomeIcons.yoast;
    case 'fa-youtube':
      return FontAwesomeIcons.youtube;
    default:
      return FontAwesomeIcons.cubes;
  }
}
